name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    strategy:
      matrix: 
        # sbcl32 and clisp32 don't work, clasp won't build on CI servers?
        lisp: [sbcl-bin, sbcl, ccl,ccl32,ecl,clisp,allegro,cmucl,abcl]
        #lisp: [sbcl, ccl, ecl, cmucl]
        # lisp: [ ecl, ccl-bin  ]
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ windows-latest ]
        #os: [ubuntu-latest]
        exclude:
          # ccl doesn't seem to work on osx?
            - os: macos-latest
              lisp: ccl
          # msys or something doesn't work on windows runners?
            - os: windows-latest
              lisp: ecl
          # clisp doesn't build on windows runner
            - os: windows-latest
              lisp: clisp
          #  
          # ccl never exits on win?
            - os: windows-latest
              lisp: ccl
          # skip 32bit lisps on osx
            - os: macos-latest
              lisp: sbcl32
            - os: macos-latest
              lisp: ccl32
            - os: macos-latest
              lisp: clisp32
            - os: macos-latest
              lisp: allegro
            - os: macos-latest
              lisp: cmucl
      fail-fast: false
      
    runs-on: ${{ matrix.os }}
    
    steps:
    # Check out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # check out extra repo if not in QL, or version in ql is too old
    - run: mkdir -p ~/lisp/
    - name: trivial-features from git
      uses: actions/checkout@v2
      with:
        repository: trivial-features/trivial-features
        path: ~/lisp/trivial-features
    - name: mmap from git
      uses: actions/checkout@v2
      with:
        repository: Shinmera/mmap
        path: ~/lisp/mmap
    
    - name: calculate cache name
      run: echo "::set-env name=cache-key::$(date +%B%d)"
   
    - name: caches
      shell: bash
      run: |
        echo cache key = ${{ env.cache-key }}
        echo ${{ runner.os }}-${{ matrix.lisp }}-dot-roswell-${{ hashFiles('**/*.asd') }}
    
    - name: cache .roswell
      id: cache-dot-roswell
      uses: actions/cache@v1
      with:
        path: ~/.roswell
        key: ${{ runner.os }}-${{ matrix.lisp }}-dot-roswell-${{ hashFiles('**/*.asd') }}
        restore-keys: ${{ runner.os }}-${{ matrix.lisp }}-dot-roswell-
        
    - name: install roswell
      # always run install, since it does some global installs and setup that isn't cached
      env:
       LISP: ${{ matrix.lisp }}
      #run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      run: curl -L https://raw.githubusercontent.com/3b/roswell/master/scripts/install-for-ci.sh | sh
    
    - name: run lisp
      continue-on-error: true
      shell: bash
      run: |
        echo 1
        echo "path=$PATH"
        ros -v -v -e '(format t "~a:~a on ~a~%...~%~%" (lisp-implementation-type) (lisp-implementation-version) (machine-type))' -e '(format t "q-o-e = ~s~%" *quit-on-eof*)' -e '(setf *quit-on-eof* t)' -e '(quit)' -e '(format t "---~%")' -e '(uiop:quit 1 t)' -e '(format t "??~%")' -q -e '(format t "!?~%")'
        echo 3
        ros -e '(format t " fixnum bits:~a~%" (integer-length most-positive-fixnum))' -q
        ros -e "(format t \"tf = ~s~%\" (ql:where-is-system 'trivial-features))" -q
        ros -e "(format t \"pngload= ~s~%\" (ql:where-is-system 'pngload))" -q
        ros -e '(format t "init features = ~s~%" *features*)' -q
        ros -e "(ql:quickload 'trivial-features)" -e '(format t "features = ~s~%" *features*)'-q
        ls -lR ~/lisp
        
    - name: load code from clean fasl cache
      #if: matrix.os != 'windows-latest'
      shell: bash
      run: |
        rm -rf ~/.cache/common-lisp/
        mkdir -p ~/.cache/common-lisp/
        ros -e "(ql:quickload 'testing123)" -q
        
    - name: load code from fasls and run tests
      shell: bash
      run: ros -e "(ql:quickload :testing123)" -e "(pngload.test:test-images)" -q
        
    - name: test read times
      shell: bash
      run: |
        curl http://3bb.cc/tmp/fft.png -o /tmp/fft.png
        ros -e "(ql:quickload 'testing123)" -e '(pngload.test:test-read-times "/tmp/fft.png" :count 10)' -q

