name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        # specify shell explicitly to get msys instead of git-bash on windows
        # shell: bash --login -eo pipefail "{0}"
        shell: ${{ fromJSON('[ "bash", "msys2 {0}" ]') [ matrix.os == 'windows-latest' ] }}

    steps:

    - uses: msys2/setup-msys2@v2
      if: matrix.os == 'windows-latest'
      with:
        path-type: inherit
        msystem: MINGW64
        release: false
        update: false


    - name: windows specific settings
      if: matrix.os == 'windows-latest'
      run: |
        git config --global core.autocrlf false
        # make sure MSYSCON is set so roswell doesn't try to install msys
        echo "MSYSCON=defterm" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "$HOME/.roswell/bin" | Out-File -FilePath $env:GITHUB_PATH -Append
        # echo "$HOME/.roswell/lisp/quicklisp/bin" | Out-File -FilePath $env:GITHUB_PATH -Append

    - uses: actions/checkout@v2
      # check out into subdir so we can pull other projects next to it.
      # roswell CI script sets up current dir as asdf search tree
      with:
        path: test-scratch

    - name: ci-utils fork
      uses: actions/checkout@v2
      with:
        repository: 3b/ci-utils
        ref: test2
        path: ci-utils


    - name: Print system version
      run: |
        uname

    - name: caches
      run: |
        echo cache key = ${{ env.cache-key }}
        echo ${{ runner.os }}-${{ matrix.lisp }}-dot-roswell-${{ hashFiles('**/*.asd') }}


    - name: cache .roswell
      id: cache-dot-roswell
      uses: actions/cache@v1
      with:
        path: ~/.roswell
        key: ${{ runner.os }}-${{ matrix.lisp }}-dot-roswell-${{ hashFiles('**/*.asd') }}
        restore-keys: ${{ runner.os }}-${{ matrix.lisp }}-dot-roswell-

    - name: install roswell
      # always run install, since it does some global installs and setup that isn't cached
      env:
       LISP: ${{ matrix.lisp }}
      run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh -x

    - name: install ci-utils
      run: |
        ros install ci-utils
        echo "$HOME/.roswell/bin" >> $GITHUB_PATH
        echo "$HOME/.roswell/bin"


    - name: run lisp
      continue-on-error: true
      run: |
        echo 1
        echo "path=$PATH"
        ros -e '(format t "~a:~a on ~a~%...~%~%" (lisp-implementation-type) (lisp-implementation-version) (machine-type))'
        echo 3
        ros -e '(format t " fixnum bits:~a~%" (integer-length most-positive-fixnum))'
        ros -e "(format t \"tf = ~s~%\" (ql:where-is-system 'trivial-features))"
        ros -e "(format t \"pngload= ~s~%\" (ql:where-is-system 'pngload))"
        ros -e '(format t "init features = ~s~%" *features*)'
        ros -e "(ql:quickload 'trivial-features)" -e '(format t "features = ~s~%" *features*)'

    - name: clear fasl cache
      run: |
        [ -d $USERPROFILE/AppData/Local/cache/common-lisp/ ] && rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/
        [ -d ~/.cache/common-lisp/ ] &7 rm -rf ~/.cache/common-lisp/
        mkdir -p ~/.cache/common-lisp/

    - name: load code from clean fasl cache
      run: |
        set -e
        run-test-forms -r 0x3b -l testing123 "pass"
        [ $? -eq 0x3b ]

    - name: load code from fasl
      run: |
        set -e
        run-test-forms -r 0x3b -l testing123 "pass"
        [ $? -eq 0x3b ]

    - name: fail
      run: |
        set -e
        run-test-forms -r 0x3b -l testing123 "fail"
        [ $? -eq 1 ]
        run-test-forms -r 0x3b -l testing123 "error"
        [ $? -eq 2 ]

