name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    strategy:
      matrix: 
        lisp: [0,1,2,3,4,5,6,7,8]
        os: [windows-latest]
      fail-fast: false
      
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ fromJSON('[ "bash", "msys2 {0}" ]') [ matrix.os == 'windows-latest' ] }}
    
    steps:
    # Check out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Print system version
      run: |
        uname
    - name: caches
      run: |
        echo cache key = ${{ env.cache-key }}
        echo ${{ runner.os }}-${{ matrix.lisp }}-dot-roswell-${{ hashFiles('**/*.asd') }}
    

    - name: cache ql
      id: cache-dot-roswell
      uses: actions/cache@v1
      with:
        path: ~/.roswell
        key: ${{ runner.os }}-ql-${{ hashFiles('**/*.asd') }}
        restore-keys: ${{ runner.os }}-${{ matrix.lisp }}-dot-roswell-
    
    - name: install sbcl
      run: |
         wget ${{ fromJSON('[ "https://github.com/sbcl/sbcl/suites/4748258805/artifacts/131406809",
                              "https://github.com/sbcl/sbcl/suites/4748051802/artifacts/131393844",
                              "https://github.com/sbcl/sbcl/suites/4746608398/artifacts/131309989",
                              "https://github.com/sbcl/sbcl/suites/4734271318/artifacts/130585775",
                              "https://github.com/sbcl/sbcl/suites/4682480164/artifacts/127559464",
                              "https://github.com/sbcl/sbcl/suites/4610434975/artifacts/124607170",
                              "https://github.com/sbcl/sbcl/suites/4511919320/artifacts/120559656",
                              "https://github.com/sbcl/sbcl/suites/4509503715/artifacts/120465184" ]') [ matrix.lisp ] }}
         unzip -v sbcl-windows-installer
         msiexec -p sbcl*.msi
         
    - name: install ql
      run: |
         wget https://beta.quicklisp.org/quicklisp.lisp
         sbcl --load quicklisp.lisp --eval "(quicklisp-quickstart:install)" --eval "(ql:without-prompting (ql:add-to-init-file))"
         
    - name: run lisp
      continue-on-error: true
      run: |
        echo 1
        echo "path=$PATH"
        sbcl --eval '(format t "~a:~a on ~a~%...~%~%" (lisp-implementation-type) (lisp-implementation-version) (machine-type))' --quit
        echo 3
        sbcl --eval '(format t " fixnum bits:~a~%" (integer-length most-positive-fixnum))' --quit
        sbcl --eval "(format t \"tf = ~s~%\" (ql:where-is-system 'trivial-features))" --quit
        sbcl --eval "(format t \"cffi= ~s~%\" (ql:where-is-system 'cffi))" --quit
        sbcl --eval '(format t "init features = ~s~%" *features*)' --quit
      
    - name: run 0
      continue-on-error: true
      run: |
          rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
          sbcl --eval "(ql:quickload 'cffi)" --quit
          
    - name: run 1
      continue-on-error: true
      run: |
          rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
          sbcl --eval "(ql:quickload 'cffi)" --quit

    - name: run 2
      continue-on-error: true
      run: |
          rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
          sbcl --eval "(ql:quickload 'cffi)" --quit
          
    - name: run 3
      continue-on-error: true
      run: |
          rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
          sbcl --eval "(ql:quickload 'cffi)" --quit
          
    - name: run 4
      continue-on-error: true
      run: |
          rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
          sbcl --eval "(ql:quickload 'cffi)" --quit
          
