name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  roswell-root: ~/roswell
  ROSWELL_DIR: ~/roswell/.roswell
  ROSWELL_INSTALL_DIR: ~/roswell/install

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    strategy:
      matrix: 
        # sbcl32 and clisp32 don't work, clasp won't build on CI servers?
        #lisp: [sbcl-bin,ccl,ccl32,ecl,clisp,allegro]
        lisp: [sbcl-bin, ccl]
        os: [ubuntu-latest] #, macos-latest]
      fail-fast: false
      
    runs-on: ${{ matrix.os }}
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: calculate cache name
      run: echo "::set-env name=cache-key::$(date +%B%d)"
   
    - name: caches
      run: |
        echo cache key = ${{ env.cache-key }}
        echo ${{ runner.os }}-${{ matrix.lisp }}-dot-roswell-${{ hashFiles('**/*.asd') }}

    
    - name: cache roswell install
      id: cache-roswell
      uses: actions/cache@v1
      with:
        path: ${{ env.roswell-root }}
        key: ${{ runner.os }}-${{ matrix.lisp }}-roswell-${{ hashFiles('**/*.asd') }}
    
    - name: cache .config
      id: cache-dot-config
      uses: actions/cache@v1
      with:
        path: ~/.config/common-lisp # wrong on windows :/
        key: ${{ runner.os }}-${{ matrix.lisp }}-dot-config-${{ hashFiles('**/*.asd') }}
    
    - name: install roswell
      if: steps.cache-roswell.outputs.cache-hit != 'true'
      env:
       LISP: ${{ matrix.lisp }}
      run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
    
    - name: home dir
      run: |
        pwd
        echo home = $HOME
        ls -la $HOME
        ls -laR $HOME/roswell
        ls -laR $HOME/.config
        ls -laR $HOME/.cache
        ls -laR $HOME/lisp


    - name: run lisp
      run: |
        ros -e '(format t "~a:~a on ~a~%" (lisp-implementation-type) (lisp-implementation-version) (machine-type))'
        ros -e '(format t " fixnum bits:~a~%" (integer-length most-positive-fixnum))'
